apiVersion: v1
kind: Service
metadata:
  name: sptc-application-service
  namespace: sptc-application
  labels:
    app: sptc-application
    app.kubernetes.io/name: sptc-application
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: sptc-application
